# Generated by Django 2.1 on 2018-09-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseditorials',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
