# Generated by Django 2.1 on 2018-09-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180831_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseditorials',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
